package views;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author mateo
 */
public class SectionsWindow extends javax.swing.JFrame {

    private ImageIcon image1, image2, image3;
    private JPanel seccionOnePanel, seccionTwoPanel, seccionThreePanel;
    private boolean key;

    /**
     * Creates new form SectionsWindow
     */
    public SectionsWindow() {
        panelsSeccion();
        initComponents();
        image1 = new ImageIcon("src/pictures/adidas_savage.gif");
        setImageLabel(seccionOneButton, image1);
        image2 = new ImageIcon("src/pictures/ropa_adidas.png");
        setImageLabel(seccionTwoButton, image2);
        image3 = new ImageIcon("src/pictures/adidas_messi.gif");
        setImageLabel(seccionThreeButton, image3);
        this.key = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        seccionOneButton = new javax.swing.JButton();
        seccionTwoButton = new javax.swing.JButton();
        seccionThreeButton = new javax.swing.JButton();
        finishConexionButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Secciones del Jugador");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        mainPanel.setBackground(new java.awt.Color(0, 0, 0));

        seccionOneButton.setBackground(new java.awt.Color(0, 0, 0));

        seccionTwoButton.setBackground(new java.awt.Color(0, 0, 0));

        seccionThreeButton.setBackground(new java.awt.Color(0, 0, 0));

        finishConexionButton.setText("Finalizar conexión");

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(seccionOneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seccionTwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seccionThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(finishConexionButton))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seccionThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seccionTwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seccionOneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(finishConexionButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void actionListenerFinishConexion(ActionListener listener) {
        finishConexionButton.addActionListener(listener);
    }

    public void actionListenerSeccionOne(ActionListener listener) {
        seccionOneButton.addActionListener(listener);
    }

    public void actionListenerSeccionTwo(ActionListener listener) {
        seccionTwoButton.addActionListener(listener);
    }

    public void actionListenerSeccionThree(ActionListener listener) {
        seccionThreeButton.addActionListener(listener);
    }

    public void setImageLabel(JButton button, ImageIcon imagen) {
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(button.getWidth(), button.getHeight(), Image.SCALE_DEFAULT));
        button.setIcon(icono);
    }

    public void panelsSeccion() {
        seccionOnePanel = new JPanel();
        seccionOnePanel.setBackground(Color.red);
        seccionOnePanel.setBounds(0, 0, 1000, 550);
        seccionOnePanel.setLayout(null);
        seccionOnePanel.setVisible(key);
        this.add(seccionOnePanel);

        seccionTwoPanel = new JPanel();
        seccionTwoPanel.setBackground(Color.blue);
        seccionTwoPanel.setBounds(0, 0, 1000, 550);
        seccionTwoPanel.setLayout(null);
        seccionTwoPanel.setVisible(key);
        this.add(seccionTwoPanel);

        seccionThreePanel = new JPanel();
        seccionThreePanel.setBackground(Color.black);
        seccionThreePanel.setBounds(0, 0, 1000, 550);
        seccionThreePanel.setLayout(null);
        seccionThreePanel.setVisible(key);
        this.add(seccionThreePanel);
    }

    /*public void setVisibleJPanels(ActionEvent e) {
        System.out.println("111111111");
        if (e.getSource().equals(seccionOneButton)) {
            System.out.println("22222222222222");
            mainPanel.removeAll();
            this.key = true;
            this.seccionOnePanel.setVisible(key);
            System.out.println("/////////////////");
        }
        /*else if (e.getSource() == seccionTwoButton) {
            seccionOne.setVisible(false);
            seccionTwo.setVisible(true);
            seccionThree.setVisible(false);
        } else if (e.getSource() == seccionThreeButton){
            seccionOne.setVisible(false);
            seccionTwo.setVisible(false);
            seccionThree.setVisible(true);
        } else {
            System.out.println("error");
        }
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finishConexionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton seccionOneButton;
    private javax.swing.JButton seccionThreeButton;
    private javax.swing.JButton seccionTwoButton;
    // End of variables declaration//GEN-END:variables

    public JButton getSeccionOneButton() {
        return seccionOneButton;
    }

    public JButton getSeccionThreeButton() {
        return seccionThreeButton;
    }

    public JButton getSeccionTwoButton() {
        return seccionTwoButton;
    }

    public JPanel getSeccionOnePanel() {
        return seccionOnePanel;
    }

    public JPanel getSeccionTwoPanel() {
        return seccionTwoPanel;
    }

    public JPanel getSeccionThreePanel() {
        return seccionThreePanel;
    }
    
    public JPanel getMainPanel() {
        return mainPanel;
    }

}
