/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.Conexion;
import ec.edu.ups.controlador.ControladorCita;
import ec.edu.ups.controlador.ControladorFacturaCab;
import ec.edu.ups.controlador.ControladorFacturaDet;
import ec.edu.ups.controlador.ControladorMascota;
import ec.edu.ups.controlador.ControladorPersona;
import ec.edu.ups.controlador.ControladorServicio;
import ec.edu.ups.controlador.ControladorTipoMascota;
import ec.edu.ups.controlador.ControladorUsuario;
import ec.edu.ups.modelo.Usuario;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author guama
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    public static Menu_Principal instance;

    private ControladorUsuario controladorUsuario;
    private ControladorPersona controladorPersona;
    private ControladorServicio controladorServicio;
    private ControladorFacturaCab controladorFacturaCab;
    private ControladorFacturaDet controladorFacturaDet;
    private ControladorTipoMascota controladorTipoMascota;
    private ControladorMascota controladorMascota;
    private ControladorCita controladorCita;
    private String[] arreglo;

    private Vent_Citas ventCit;
    private Vent_Clientes ventCli;
    private Vent_Mascotas ventMas;
    private Vent_Personal ventPer;
    private Vent_Usuarios ventUsua;
    private Vent_Servicios ventSer;
    private Vent_Facturar1 ventFac;
    private Vent_Anular ventAnu;
    private Vent_CambiarContrasenia venCa;

    public Menu_Principal() {
        instance = this;
        initComponents();
        this.controladorUsuario = new ControladorUsuario();
        this.controladorPersona = new ControladorPersona();
        this.controladorServicio = new ControladorServicio();
        this.controladorTipoMascota = new ControladorTipoMascota();
        this.controladorMascota = new ControladorMascota();
        this.controladorFacturaCab = new ControladorFacturaCab();
        this.controladorFacturaDet = new ControladorFacturaDet();
        this.controladorCita = new ControladorCita();
        this.ventCit = new Vent_Citas();
        this.ventCli = new Vent_Clientes();
        this.ventMas = new Vent_Mascotas();
        this.ventPer = new Vent_Personal();
        this.ventUsua = new Vent_Usuarios();
        this.ventSer = new Vent_Servicios();
        this.ventFac = new Vent_Facturar1();
        this.ventAnu = new Vent_Anular();
        this.venCa = new Vent_CambiarContrasenia();
        this.setLocationRelativeTo(null);
        
        Vent_Inicio ventInicio = new Vent_Inicio(controladorUsuario, this);
        jDesktopPane1.add(ventInicio);
        ventInicio.setVisible(true);
    }

    public void setArreglo(String[] arreglo) {
        this.arreglo = arreglo;

    }

    public String[] getArreglo() {
        return arreglo;
    }

    public Usuario getUsuarioSeleccionaado() {
        return controladorUsuario.getUsuarioIngresado();
    }

    public void habilitarContenido() {
        char encargo = controladorUsuario.getUsuarioIngresado().getEncargo();
        if (encargo == 'G') {
            men_Clinica.setEnabled(true);
            men_Facturacion.setEnabled(true);
            men_Cerrar_Act.setEnabled(true);
        } else if (encargo == 'A') {
            men_Clinica.setEnabled(true);
            men_Facturacion.setEnabled(true);
            men_Cerrar_Act.setEnabled(true);
            men_Adminstracion.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        men_Clinica = new javax.swing.JMenu();
        itm_Citas = new javax.swing.JMenuItem();
        itm_Clientes = new javax.swing.JMenuItem();
        itm_Mascotas = new javax.swing.JMenuItem();
        men_Adminstracion = new javax.swing.JMenu();
        itm_Personal = new javax.swing.JMenuItem();
        itm_Usuarios = new javax.swing.JMenuItem();
        itm_Servicios = new javax.swing.JMenuItem();
        men_Facturacion = new javax.swing.JMenu();
        itm_Crear_Fac = new javax.swing.JMenuItem();
        itm_Anular_Fac = new javax.swing.JMenuItem();
        men_Cerrar_Act = new javax.swing.JMenu();
        itm_Actualizar = new javax.swing.JMenuItem();
        itm_Cerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jDesktopPane1.setName(""); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/FONDOFIN.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, Short.MAX_VALUE)
        );

        men_Clinica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_clinic_25px.png"))); // NOI18N
        men_Clinica.setText("CLINICA");
        men_Clinica.setEnabled(false);

        itm_Citas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_medical_history_25px.png"))); // NOI18N
        itm_Citas.setText("CITAS");
        itm_Citas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_CitasActionPerformed(evt);
            }
        });
        men_Clinica.add(itm_Citas);

        itm_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_client_management_25px_1.png"))); // NOI18N
        itm_Clientes.setText("CLIENTES");
        itm_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_ClientesActionPerformed(evt);
            }
        });
        men_Clinica.add(itm_Clientes);

        itm_Mascotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_pets_25px.png"))); // NOI18N
        itm_Mascotas.setText("MASCOTAS");
        itm_Mascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_MascotasActionPerformed(evt);
            }
        });
        men_Clinica.add(itm_Mascotas);

        jMenuBar1.add(men_Clinica);

        men_Adminstracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_administrative_tools_25px.png"))); // NOI18N
        men_Adminstracion.setText("ADMINISTRACIÓN");
        men_Adminstracion.setEnabled(false);

        itm_Personal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_name_tag_25px.png"))); // NOI18N
        itm_Personal.setText("PERSONAL");
        itm_Personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_PersonalActionPerformed(evt);
            }
        });
        men_Adminstracion.add(itm_Personal);

        itm_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_select_users_25px_2.png"))); // NOI18N
        itm_Usuarios.setText("USUARIOS");
        itm_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_UsuariosActionPerformed(evt);
            }
        });
        men_Adminstracion.add(itm_Usuarios);

        itm_Servicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_doctors_bag_25px.png"))); // NOI18N
        itm_Servicios.setText("SERVICIOS");
        itm_Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_ServiciosActionPerformed(evt);
            }
        });
        men_Adminstracion.add(itm_Servicios);

        jMenuBar1.add(men_Adminstracion);

        men_Facturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_request_money_25px.png"))); // NOI18N
        men_Facturacion.setText("FACTURACIÓN");
        men_Facturacion.setEnabled(false);

        itm_Crear_Fac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_paid_bill_25px.png"))); // NOI18N
        itm_Crear_Fac.setText("Crear Factura");
        itm_Crear_Fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_Crear_FacActionPerformed(evt);
            }
        });
        men_Facturacion.add(itm_Crear_Fac);

        itm_Anular_Fac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_cancel_subscription_25px.png"))); // NOI18N
        itm_Anular_Fac.setText("Anular Factura");
        itm_Anular_Fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_Anular_FacActionPerformed(evt);
            }
        });
        men_Facturacion.add(itm_Anular_Fac);

        jMenuBar1.add(men_Facturacion);

        men_Cerrar_Act.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_security_configuration_25px.png"))); // NOI18N
        men_Cerrar_Act.setText("SESIÓN");
        men_Cerrar_Act.setEnabled(false);

        itm_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_password_25px.png"))); // NOI18N
        itm_Actualizar.setText("Cambiar Contraseña");
        itm_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_ActualizarActionPerformed(evt);
            }
        });
        men_Cerrar_Act.add(itm_Actualizar);

        itm_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_logout_rounded_left_25px.png"))); // NOI18N
        itm_Cerrar.setText("Cerrar Sesión");
        itm_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_CerrarActionPerformed(evt);
            }
        });
        men_Cerrar_Act.add(itm_Cerrar);

        jMenuBar1.add(men_Cerrar_Act);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itm_CitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_CitasActionPerformed
        cerrarFrames();
        jDesktopPane1.add(ventCit);
        ventCit.setControladorCita(this.controladorCita);
        ventCit.setControladorMascota(this.controladorMascota);
        ventCit.setControladorPersona(this.controladorPersona);
        ventCit.setControladorTipoMascota(this.controladorTipoMascota);
        ventCit.actulizarTabla();
        if (!ventCit.isVisible()) {
            
            ventCit.setVisible(true);
        }

    }//GEN-LAST:event_itm_CitasActionPerformed

    private void itm_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_ClientesActionPerformed
        cerrarFrames();
        ventCli.setControladorPersona(this.controladorPersona);
        ventCli.actulizarTabla();
        if (!ventCli.isVisible()) {
            jDesktopPane1.add(ventCli);
            ventCli.setVisible(true);
        }
    }//GEN-LAST:event_itm_ClientesActionPerformed

    private void itm_MascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_MascotasActionPerformed
        cerrarFrames();
        ventMas.setControladorMascota(this.controladorMascota);
        ventMas.setControladorPersona(this.controladorPersona);
        ventMas.setControladorTipoMascota(controladorTipoMascota);
        ventMas.actulizarTabla();
        if (!ventMas.isVisible()) {
            jDesktopPane1.add(ventMas);
            ventMas.setVisible(true);
        }

    }//GEN-LAST:event_itm_MascotasActionPerformed

    private void itm_PersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_PersonalActionPerformed
        cerrarFrames();
        ventPer.setControladorPersona(this.controladorPersona);
        ventPer.actulizarTabla();
        if (!ventPer.isVisible()) {
            jDesktopPane1.add(ventPer);
            ventPer.setVisible(true);
        }

    }//GEN-LAST:event_itm_PersonalActionPerformed

    private void itm_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_UsuariosActionPerformed
        cerrarFrames();
        ventUsua.setControladorPersona(controladorPersona);
        ventUsua.setControladorUsuario(controladorUsuario);
        ventUsua.actulizarTabla();
        if (!ventUsua.isVisible()) {
            jDesktopPane1.add(ventUsua);
            ventUsua.setVisible(true);
        }

    }//GEN-LAST:event_itm_UsuariosActionPerformed

    private void itm_ServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_ServiciosActionPerformed
        cerrarFrames();
        ventSer.setControladorServicio(controladorServicio);
        ventSer.actulizarTabla();
        if (!ventSer.isVisible()) {
            jDesktopPane1.add(ventSer);
            ventSer.setVisible(true);
        }

    }//GEN-LAST:event_itm_ServiciosActionPerformed

    private void itm_Crear_FacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_Crear_FacActionPerformed
        cerrarFrames();
        ventFac.setControladorPersona(controladorPersona);
        ventFac.setControladorServicio(controladorServicio);
        ventFac.setControladorFacturaCab(controladorFacturaCab);
        ventFac.setControladorFacturaDet(controladorFacturaDet);
        if (!ventFac.isVisible()) {
            jDesktopPane1.add(ventFac);
            ventFac.setVisible(true);
        }
    }//GEN-LAST:event_itm_Crear_FacActionPerformed

    private void itm_Anular_FacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_Anular_FacActionPerformed
        cerrarFrames();
        ventAnu.setControladorFacturaCab(controladorFacturaCab);
        ventAnu.setControladorFacturaDet(controladorFacturaDet);
        ventAnu.setControladorPersona(controladorPersona);
        ventAnu.actulizarTabla();
        if (!ventAnu.isVisible()) {
            jDesktopPane1.add(ventAnu);
            ventAnu.setVisible(true);
        }

    }//GEN-LAST:event_itm_Anular_FacActionPerformed

    private void itm_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_ActualizarActionPerformed
        cerrarFrames();
        venCa.setControladorUsuario(this.controladorUsuario);
        venCa.setMenu_Principal(this);
        venCa.obtenerUsuario();
        venCa.vaciar();
        if (!venCa.isVisible()) {
            jDesktopPane1.add(venCa);
            venCa.setVisible(true);
        }

    }//GEN-LAST:event_itm_ActualizarActionPerformed

    public void cerrarFrames(){
        JInternalFrame[] allFrames = this.jDesktopPane1.getAllFrames();
        for (JInternalFrame internalFrame : allFrames) {
            internalFrame.dispose();
            jDesktopPane1.remove(internalFrame);
        }
    }
    public void descativar() {
        men_Clinica.setEnabled(false);
        men_Facturacion.setEnabled(false);
        men_Cerrar_Act.setEnabled(false);
        men_Adminstracion.setEnabled(false);
        cerrarFrames();
    }

    private void itm_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_CerrarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de cerrar Sesion?", "Confirmar Cierre de Sesion", JOptionPane.OK_CANCEL_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            descativar();

            this.controladorUsuario.setUsuarioIngresado(null);
            Vent_Inicio ventInicio = new Vent_Inicio(this.controladorUsuario, this);
            jDesktopPane1.add(ventInicio);
            ventInicio.setVisible(true);
        }
    }//GEN-LAST:event_itm_CerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itm_Actualizar;
    private javax.swing.JMenuItem itm_Anular_Fac;
    private javax.swing.JMenuItem itm_Cerrar;
    private javax.swing.JMenuItem itm_Citas;
    private javax.swing.JMenuItem itm_Clientes;
    private javax.swing.JMenuItem itm_Crear_Fac;
    private javax.swing.JMenuItem itm_Mascotas;
    private javax.swing.JMenuItem itm_Personal;
    private javax.swing.JMenuItem itm_Servicios;
    private javax.swing.JMenuItem itm_Usuarios;
    public javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu men_Adminstracion;
    private javax.swing.JMenu men_Cerrar_Act;
    private javax.swing.JMenu men_Clinica;
    private javax.swing.JMenu men_Facturacion;
    // End of variables declaration//GEN-END:variables
}
