/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorServicio;
import ec.edu.ups.modelo.Servicio;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guama
 */
public class Vent_Servicios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vent_Servicios
     */
    private ControladorServicio controladorServicio;
    private List<Servicio> listaServicios;
    private List<Servicio> listaActual;
    private Servicio servicioSeleccionado;
    private boolean procesandoEvento = false;

    public Vent_Servicios() {
        initComponents();

        tabla_Servicios.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                // obtener la fila seleccionada
                if (!procesandoEvento) {
                    procesandoEvento = true;
                    int filaSeleccionada = tabla_Servicios.getSelectedRow();
                    System.out.println("Fila seleccionada: " + filaSeleccionada);
                    if (filaSeleccionada != -1) {
                        System.out.println("Servicio seleccionado: " + listaActual.get(filaSeleccionada).toString());
                        servicioSeleccionado = listaActual.get(filaSeleccionada);
                        actEli_Servicio();
                    }
                    procesandoEvento = false;
                }
            }
        });
    }

    public void actEli_Servicio() {
        tabla_Servicios.setEnabled(false);
        btn_Registrar.setEnabled(false);
        btn_Buscar.setEnabled(false);
        btn_Modificar.setEnabled(true);
        btn_Eliminar.setEnabled(true);
        combo_Estado.setEnabled(true);
        txt_Nombre.setText(servicioSeleccionado.getNombre());
        txt_Precio.setText("" + servicioSeleccionado.getPrecio());

        if (servicioSeleccionado.getIva() == 'S') {
            combo_IVA.setSelectedItem("SI");
        } else {
            combo_IVA.setSelectedItem("NO");
        }
        if (servicioSeleccionado.getEstado() == 'S') {
            combo_Estado.setSelectedItem("Activo");
        } else {
            combo_Estado.setSelectedItem("Inactivo");
        }

    }

    public void setControladorServicio(ControladorServicio controladorServicio) {
        this.controladorServicio = controladorServicio;
    }

    public void actulizarTabla() {
        listaServicios = this.controladorServicio.listarServicios();
        listaActual = listaServicios;
        DefaultTableModel modelo = (DefaultTableModel) tabla_Servicios.getModel();

        modelo.setRowCount(0);

        for (Servicio ser : listaServicios) {
            System.out.println(ser.toString());

            String iva;
            String estado;

            if (ser.getIva() == 'S') {
                iva = "Si";
            } else {
                iva = "No";
            }

            if (ser.getEstado() == 'S') {
                estado = "Activo";
            } else {
                estado = "Inactivo";
            }

            Object[] fila = {ser.getId(), ser.getNombre(), ser.getPrecio(), iva, estado};
            modelo.addRow(fila);
        }

        tabla_Servicios.setModel(modelo);

    }

    public void resultadoBusqueda(List<Servicio> servicios) {
        DefaultTableModel modelo = (DefaultTableModel) tabla_Servicios.getModel();

        modelo.setRowCount(0);

        for (Servicio ser : servicios) {
            System.out.println(ser.toString());
            String iva;
            String estado;

            if (ser.getIva() == 'S') {
                iva = "Si";
            } else {
                iva = "No";
            }

            if (ser.getEstado() == 'S') {
                estado = "Activo";
            } else {
                estado = "Inactivo";
            }

            Object[] fila = {ser.getId(), ser.getNombre(), ser.getPrecio(), iva, estado};
            modelo.addRow(fila);
        }
        listaActual = servicios;

        tabla_Servicios.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Precio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        combo_Estado = new javax.swing.JComboBox<>();
        btn_Buscar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        btn_Modificar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_Registrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Servicios = new javax.swing.JTable();
        combo_IVA = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(29, 64, 97));
        jLabel3.setText("Nombre Servicio*");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        txt_Nombre.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombreActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 250, 30));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(29, 64, 97));
        jLabel4.setText("Precio*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, -1, -1));

        txt_Precio.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PrecioActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 250, 30));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(29, 64, 97));
        jLabel8.setText("Estado*");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        combo_Estado.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        combo_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        combo_Estado.setEnabled(false);
        combo_Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_EstadoActionPerformed(evt);
            }
        });
        jPanel1.add(combo_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 250, 30));

        btn_Buscar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btn_Buscar.setForeground(new java.awt.Color(29, 64, 97));
        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_search_50px.png"))); // NOI18N
        btn_Buscar.setText("BUSCAR");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 630, -1, -1));

        btn_Cancelar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btn_Cancelar.setForeground(new java.awt.Color(29, 64, 97));
        btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_cancel_50px.png"))); // NOI18N
        btn_Cancelar.setText("CANCELAR");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 630, -1, -1));

        btn_Modificar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btn_Modificar.setForeground(new java.awt.Color(29, 64, 97));
        btn_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_edit_property_50px.png"))); // NOI18N
        btn_Modificar.setText("MODIFICAR");
        btn_Modificar.setEnabled(false);
        btn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 630, -1, -1));

        btn_Eliminar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btn_Eliminar.setForeground(new java.awt.Color(29, 64, 97));
        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_Delete_50px.png"))); // NOI18N
        btn_Eliminar.setText("ELIMINAR");
        btn_Eliminar.setEnabled(false);
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 630, -1, -1));

        btn_Registrar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btn_Registrar.setForeground(new java.awt.Color(29, 64, 97));
        btn_Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/icons8_add_50px_1.png"))); // NOI18N
        btn_Registrar.setText("REGISTRAR");
        btn_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 630, -1, -1));

        tabla_Servicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre", "Precio", "IVA", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_Servicios);
        if (tabla_Servicios.getColumnModel().getColumnCount() > 0) {
            tabla_Servicios.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 840, 280));

        combo_IVA.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        combo_IVA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        jPanel1.add(combo_IVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 140, 250, 30));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(29, 64, 97));
        jLabel9.setText("Tiene Iva*");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/Servicios.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreActionPerformed

    private void txt_PrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PrecioActionPerformed

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        Buscar_Servicio ser = new Buscar_Servicio();
        ser.setVent_Servicios(this);
        ser.setControladorServicio(this.controladorServicio);
        ser.setVisible(true);
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        resetear();
        actulizarTabla();
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModificarActionPerformed
        if (txt_Nombre.getText().trim().isEmpty() || txt_Precio.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ningun campo puede estar vacío");
        } else {
            Servicio serUpdate = new Servicio();
            serUpdate.setId(servicioSeleccionado.getId());
            serUpdate.setNombre(txt_Nombre.getText().trim());
            serUpdate.setPrecio(Double.parseDouble(txt_Precio.getText().trim()));

            if (combo_IVA.getSelectedIndex() == 0) {
                serUpdate.setIva('S');
            } else {
                serUpdate.setIva('N');
            }
            if (combo_Estado.getSelectedIndex() == 0) {
                serUpdate.setEstado('S');
            } else {
                serUpdate.setEstado('N');
            }
            this.controladorServicio.actualizarServicio(serUpdate);
        }
        actulizarTabla();
        resetear();
    }//GEN-LAST:event_btn_ModificarActionPerformed

    private void combo_EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_EstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_EstadoActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        this.controladorServicio.eliminarServicio(servicioSeleccionado);
        resetear();
        actulizarTabla();
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btn_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarActionPerformed
        if (txt_Nombre.getText().trim().isEmpty() || txt_Precio.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ningun campo puede estar vacío");
        } else {
            char iva;
            if (combo_IVA.getSelectedIndex() == 0) {
                iva = 'S';
            } else {
                iva = 'N';;
            }
            Double precio=null;
            Boolean flag=false;
            try {
                precio=Double.parseDouble(txt_Precio.getText().trim());
                flag=true;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ingrese un numero valido");
            }
            
            if (flag) {
                this.controladorServicio.registrarServicio(new Servicio(0, precio, txt_Nombre.getText().trim(), iva, 'S'));
            }

            
        }
        resetear();
        actulizarTabla();
    }//GEN-LAST:event_btn_RegistrarActionPerformed

    public void resetear() {
        txt_Nombre.setText("");
        txt_Precio.setText("");
        tabla_Servicios.setEnabled(true);
        btn_Registrar.setEnabled(true);
        btn_Buscar.setEnabled(true);
        btn_Modificar.setEnabled(false);
        btn_Eliminar.setEnabled(false);
        combo_Estado.setEnabled(false);
        combo_Estado.setSelectedItem("Activo");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Modificar;
    private javax.swing.JButton btn_Registrar;
    private javax.swing.JComboBox<String> combo_Estado;
    private javax.swing.JComboBox<String> combo_IVA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_Servicios;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Precio;
    // End of variables declaration//GEN-END:variables
}
