/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import cotroler.Controler;
import javax.swing.ComboBoxModel;


/**
 *
 * @author Anthony Moya
 */
public class GradeWindowView extends GradeView {
    private Controler c;
    /**
     * Creates new form Grade
     */
    public GradeWindowView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradebuttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        excelentButton = new javax.swing.JButton();
        goodButton = new javax.swing.JButton();
        regularButton = new javax.swing.JButton();
        badButton = new javax.swing.JButton();
        worstButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        dependentsComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setText("GRACIAS POR USAR NUESTROS SERVICIOS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Calificacion"));
        jPanel1.setLayout(new java.awt.GridLayout(5, 0));

        excelentButton.setText("Excelente");
        excelentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excelentButtonActionPerformed(evt);
            }
        });
        jPanel1.add(excelentButton);

        goodButton.setText("Bueno");
        goodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goodButtonActionPerformed(evt);
            }
        });
        jPanel1.add(goodButton);

        regularButton.setText("Regular");
        regularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regularButtonActionPerformed(evt);
            }
        });
        jPanel1.add(regularButton);

        badButton.setText("Malo");
        badButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badButtonActionPerformed(evt);
            }
        });
        jPanel1.add(badButton);

        worstButton.setText("Pésimo");
        worstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                worstButtonActionPerformed(evt);
            }
        });
        jPanel1.add(worstButton);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Califique su experiencia de atencion");

        dependentsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dependentsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dependentsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excelentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excelentButtonActionPerformed
        c.dependentGrade(5);
    }//GEN-LAST:event_excelentButtonActionPerformed

    private void goodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goodButtonActionPerformed
        c.dependentGrade(4);
    }//GEN-LAST:event_goodButtonActionPerformed

    private void regularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regularButtonActionPerformed
        c.dependentGrade(3);
    }//GEN-LAST:event_regularButtonActionPerformed

    private void badButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badButtonActionPerformed
        c.dependentGrade(2);
    }//GEN-LAST:event_badButtonActionPerformed

    private void worstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_worstButtonActionPerformed
        c.dependentGrade(1);
    }//GEN-LAST:event_worstButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradeWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradeWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradeWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradeWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GradeWindowView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton badButton;
    private javax.swing.JComboBox dependentsComboBox;
    private javax.swing.JButton excelentButton;
    private javax.swing.JButton goodButton;
    private javax.swing.ButtonGroup gradebuttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton regularButton;
    private javax.swing.JButton worstButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setControler(Controler c) {
        this.c = c;  
    }

    @Override
    public void setVisibleWindow() {
        this.setVisible(true);
    }

    @Override
    public void setModelDependents(ComboBoxModel dependentModel) {
        this.dependentsComboBox.setModel(dependentModel);
    }

   
    @Override
    public String getDependentName() {
        return dependentsComboBox.getSelectedItem().toString();
    }


}
